[package]
name = "doomsday"
version = "0.1.0"
authors = ["Ayrat Badykov <ayratin555@gmail.com>"]

[dependencies]
chrono = "0.4"
notify-rust = "3"
schedule = { git = "https://github.com/mehcode/schedule-rs" }